Fix build: import objc/message.h for objc_msgSend
Tweak.xm:107 used objc_msgSend but only objc/runtime.h was imported,
causing 'use of undeclared identifier objc_msgSend' on CI.